<?php
$menu['admin']= array(
    'class' => "header",
    'title' => 'ดูแลระบบ',
    'cond' => current_user('user_type')=='admin',
    'bullet' => 'nature_people',
    'color' => 'col-green',
    'item' => array(
        //'billing' => array('bullet' => '',
            //'title' => 'ค่าบริการ',
            //'url' => 'main/admin/billing/manage',
            //'cond' => true,
            //),
            'setting' => array('bullet' => '',
                    'title' => 'ตั้งค่าระบบ',
                    'url' => 'main/admin/config/setting',
                    'cond' => true,
                    ),
            'checking' => array('bullet' => '',
                    'title' => 'ตั้งค่าการเช็คชื่อ',
                    'url' => 'main/admin/checking/setting',
                    'cond' => true,
                    ),
            'evaluate' => array('bullet' => '',
                            'title' => 'ตั้งค่าการประเมินผล',
                            'url' => 'main/admin/evaluate/setting',
                            'cond' => true,
                            ),
            'managestudent' => array('bullet' => '',
                    'title' => 'กลุ่มผู้เรียน',
                    'url' => 'main/admin/managestudent/list',
                    'cond' => true,
                    ),
                'manageuser' => array('bullet' => '',
                        'title' => 'รายชื่อบุคลากร',
                        'url' => 'main/admin/manageuser/list',
                        'cond' => true,
                        ),
        'rmsTransfer' => array('bullet' => '',
                'title' => 'โอนข้อมูลระบบ RMS',
                'url' => 'main/admin/rmsTransfer/panel',
                'cond' => true,
                ),
                'gradeTransfer' => array('bullet' => '',
                'title' => 'ส่งผลกิจกรรมเข้าระบบ RMS',
                'url' => 'main/admin/gradeTransfer/panel',
                'cond' => true,
                ),
                'holiday' => array('bullet' => '',
                        'title' => 'วันหยุด',
                        'url' => 'main/admin/holiday/list',
                        'cond' => true,
                        ),
            ),
        
    );